//! The static report: facts in, one self-contained HTML file out.
//!
//! Renders from [`Summary`] alone — never from the transcript — so the
//! extractor/renderer seam stays honest and `kagviz show <id> --json` output
//! is a valid input. Nothing here computes a number; if a value is not already
//! in the facts, it does not appear on the page.
//!
//! Self-contained is a hard requirement, not a preference: no external fonts,
//! stylesheets, scripts or images, so the file still renders correctly with no
//! network in five years, and can be mailed or archived as one artifact.

use crate::fmt;
use crate::summary::{Bucket, Involvement, Summary};
use chrono::{DateTime, SecondsFormat, Utc};
use std::collections::BTreeMap;

/// Render the whole report.
pub fn report(s: &Summary) -> String {
    let mut h = String::with_capacity(32 * 1024);
    h.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n");
    h.push_str("<meta charset=\"utf-8\">\n");
    h.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    h.push_str(&format!("<title>{}</title>\n", esc(&title(s))));
    h.push_str("<style>\n");
    h.push_str(CSS);
    h.push_str("</style>\n</head>\n<body>\n<main>\n");

    header(&mut h, s);
    if s.skipped_lines > 0 {
        h.push_str(&format!(
            "<p class=\"warn\">{} transcript line(s) did not parse. Every number below is \
             a partial reading.</p>\n",
            s.skipped_lines
        ));
    }
    headline(&mut h, s);
    time_strip(&mut h, s);
    h.push_str("<div class=\"cols\">\n");
    tool_mix(&mut h, s);
    h.push_str("<div class=\"col\">\n");
    file_changes(&mut h, s);
    tokens(&mut h, s);
    h.push_str("</div>\n</div>\n");
    involvement(&mut h, s);
    delegation(&mut h, s);

    h.push_str(
        "<footer>Generated by kagviz. Every figure is computed from the transcript; \
                nothing here is inferred. Times are UTC.</footer>\n",
    );
    h.push_str("</main>\n</body>\n</html>\n");
    h
}

fn title(s: &Summary) -> String {
    let project = s.project.as_deref().unwrap_or("session");
    match &s.started {
        Some(t) => format!("{project} — {}", t.format("%Y-%m-%d")),
        None => project.to_string(),
    }
}

fn header(h: &mut String, s: &Summary) {
    h.push_str("<header>\n");
    h.push_str(&format!("<h1>{}</h1>\n", esc(&title(s))));
    h.push_str("<dl class=\"meta\">\n");
    meta(h, "session", s.session_id.as_deref().unwrap_or_default());
    meta(h, "cwd", s.cwd.as_deref().unwrap_or_default());
    meta(h, "branch", s.git_branch.as_deref().unwrap_or_default());
    meta(h, "cli", join(s.cli_versions.iter().cloned()));
    meta(h, "models", join(s.models.keys().cloned()));
    meta(
        h,
        "window",
        match (&s.started, &s.ended) {
            (Some(a), Some(b)) => format!("{} → {}", stamp(a), stamp(b)),
            _ => String::new(),
        },
    );
    h.push_str("</dl>\n</header>\n");
}

fn headline(h: &mut String, s: &Summary) {
    let failures = s.total_tool_failures();
    h.push_str("<section class=\"stats\">\n");
    stat(h, "active", &fmt::duration(s.active_secs), "hands on keys");
    stat(
        h,
        "wall",
        &fmt::duration(s.wall_secs),
        &format!("{} idle", fmt::duration(s.idle_secs)),
    );
    stat(
        h,
        "turns",
        &s.assistant_turns.to_string(),
        &format!("{} user prompt(s)", s.user_prompts),
    );
    stat(
        h,
        "tools",
        &s.total_tool_calls().to_string(),
        &if failures > 0 {
            format!("{failures} failed")
        } else {
            "none failed".to_string()
        },
    );
    h.push_str("</section>\n");
}

/// The time strip: uniformly-scaled buckets, with idle collapsed to a labelled
/// break rather than stretched across the page.
fn time_strip(h: &mut String, s: &Summary) {
    let a = &s.activity;
    if a.spans.is_empty() {
        return;
    }
    let peak = a.peak_records().max(1);
    let marks = marks_by_bucket(s);

    h.push_str("<section class=\"card\">\n<h2>Time</h2>\n");
    h.push_str(&format!(
        "<p class=\"note\">{} of work in {} stretch(es), {} per column. Idle gaps of \
         {}+ are collapsed to a break.</p>\n",
        fmt::duration(s.active_secs),
        a.spans.len(),
        fmt::duration(a.bucket_secs),
        fmt::duration(crate::summary::IDLE_GAP_SECS),
    ));
    // Break labels need room to sit in; past a dozen stretches there is none,
    // and the durations live in the tooltips instead.
    let roomy = a.spans.len() <= 12;
    h.push_str(&format!(
        "<div class=\"strip {}\">\n",
        if roomy { "roomy" } else { "dense" }
    ));

    for (si, span) in a.spans.iter().enumerate() {
        if span.idle_before_secs > 0 {
            let label = fmt::duration(span.idle_before_secs);
            h.push_str(&format!(
                "<div class=\"gap\" title=\"{} idle\">",
                esc(&label)
            ));
            if roomy {
                h.push_str(&format!("<span>{}</span>", esc(&label)));
            }
            h.push_str("</div>\n");
        }
        h.push_str(&format!(
            "<div class=\"span\" style=\"flex-grow:{}\">\n<div class=\"cols-b\">\n",
            span.buckets.len()
        ));
        for (bi, bucket) in span.buckets.iter().enumerate() {
            let at = span.started + chrono::Duration::seconds(bi as i64 * a.bucket_secs);
            let mark = marks.get(&(si, bi));
            column(h, bucket, peak, &at, mark);
        }
        h.push_str("</div>\n<div class=\"axis\">");
        h.push_str(&format!(
            "<span>{}</span><span>{}</span>",
            esc(&clock(&span.started)),
            esc(&fmt::duration(span.secs))
        ));
        h.push_str("</div>\n</div>\n");
    }

    h.push_str("</div>\n");
    h.push_str(
        "<p class=\"legend\"><span class=\"key bar\"></span>work \
         <span class=\"key barfail\"></span>tool failure \
         <span class=\"key mkuser\"></span>user prompt \
         <span class=\"key mkask\"></span>question asked \
         <span class=\"key gapkey\"></span>idle, collapsed</p>\n",
    );
    h.push_str("</section>\n");
}

fn column(h: &mut String, b: &Bucket, peak: u32, at: &DateTime<Utc>, mark: Option<&Mark>) {
    let pct = if b.is_empty() {
        0
    } else {
        (6 + (b.records * 94).div_ceil(peak)).min(100)
    };
    let mut tip = format!("{} · {} record(s)", clock(at), b.records);
    if b.tool_calls > 0 {
        tip.push_str(&format!(", {} tool call(s)", b.tool_calls));
    }
    if b.tool_failures > 0 {
        tip.push_str(&format!(", {} failed", b.tool_failures));
    }
    if b.output_tokens > 0 {
        tip.push_str(&format!(", {} out", fmt::count(b.output_tokens)));
    }
    if let Some(m) = mark {
        tip.push_str(" — ");
        tip.push_str(&m.tip);
    }

    let class = if b.tool_failures > 0 {
        "bar fail"
    } else {
        "bar"
    };
    h.push_str(&format!("<div class=\"col-b\" title=\"{}\">", esc(&tip)));
    match mark {
        Some(m) => h.push_str(&format!("<i class=\"mk {}\"></i>", m.class)),
        None => h.push_str("<i class=\"mk\"></i>"),
    }
    h.push_str(&format!(
        "<div class=\"track\"><div class=\"{class}\" style=\"height:{pct}%\"></div></div></div>\n"
    ));
}

/// A user-involvement marker sitting over one bucket of the strip.
struct Mark {
    class: &'static str,
    tip: String,
}

/// Map each involvement moment onto the bucket that holds it.
///
/// A moment outside every span cannot happen — spans are built from the same
/// timestamps — but one without a timestamp is simply not placed.
fn marks_by_bucket(s: &Summary) -> BTreeMap<(usize, usize), Mark> {
    let mut out: BTreeMap<(usize, usize), Mark> = BTreeMap::new();
    let width = s.activity.bucket_secs.max(1);

    for item in &s.user_involvement {
        let Some(at) = item.at() else { continue };
        let Some((si, span)) = s
            .activity
            .spans
            .iter()
            .enumerate()
            .find(|(_, sp)| at >= sp.started && at <= sp.ended)
        else {
            continue;
        };
        let bi = (((at - span.started).num_seconds() / width) as usize).min(span.buckets.len() - 1);
        let (class, tip) = match item {
            Involvement::Prompt { preview, .. } => ("mkuser", label_of(preview)),
            Involvement::Question { question, .. } => ("mkask", format!("asked: {question}")),
        };
        out.entry((si, bi))
            .and_modify(|m| {
                m.tip.push_str(" / ");
                m.tip.push_str(&tip);
            })
            .or_insert(Mark { class, tip });
    }
    out
}

fn label_of(preview: &str) -> String {
    if preview.is_empty() {
        "user pasted an attachment".to_string()
    } else {
        preview.to_string()
    }
}

fn tool_mix(h: &mut String, s: &Summary) {
    h.push_str("<section class=\"card col\">\n<h2>Tools</h2>\n");
    if s.tool_calls.is_empty() {
        h.push_str("<p class=\"note\">No tool calls in this session.</p>\n</section>\n");
        return;
    }
    let peak = s.tool_calls.values().copied().max().unwrap_or(1).max(1);
    let mut rows: Vec<(&String, &u32)> = s.tool_calls.iter().collect();
    rows.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));

    h.push_str("<ul class=\"bars\">\n");
    for (name, n) in rows {
        let failed = s.tool_failures.get(name).copied().unwrap_or(0);
        let ok = n.saturating_sub(failed);
        h.push_str(&format!(
            "<li><span class=\"name\">{}</span>\
             <span class=\"track\">\
             <span class=\"fill\" style=\"width:{:.3}%\"></span>\
             <span class=\"fill fail\" style=\"width:{:.3}%\"></span>\
             </span><span class=\"n\">{n}{}</span></li>\n",
            esc(name),
            f64::from(ok) * 100.0 / f64::from(peak),
            f64::from(failed) * 100.0 / f64::from(peak),
            if failed > 0 {
                format!(" <em>{failed} failed</em>")
            } else {
                String::new()
            },
        ));
    }
    h.push_str("</ul>\n");

    let unknown = s.tool_failures.get("<unknown>").copied().unwrap_or(0);
    if unknown > 0 {
        h.push_str(&format!(
            "<p class=\"note\">{unknown} failure(s) could not be joined to a call — the \
             matching <code>tool_use</code> is not in this transcript.</p>\n"
        ));
    }
    h.push_str("</section>\n");
}

fn file_changes(h: &mut String, s: &Summary) {
    let c = &s.changes;
    h.push_str("<section class=\"card\">\n<h2>Files</h2>\n");
    h.push_str(&format!(
        "<p class=\"big\">{} file(s) <span class=\"add\">+{}</span> \
         <span class=\"del\">−{}</span></p>\n",
        c.files_touched,
        fmt::count(c.lines_added as u64),
        fmt::count(c.lines_deleted as u64),
    ));
    if c.opaque_edits > 0 {
        h.push_str(&format!(
            "<p class=\"note unknown\">{} shell call(s) could have changed files with no \
             recoverable diff. Those edits are <strong>not</strong> in the counts above — \
             an unknown, not a zero.</p>\n",
            c.opaque_edits
        ));
    }
    h.push_str("</section>\n");
}

fn tokens(h: &mut String, s: &Summary) {
    let t = &s.tokens;
    h.push_str("<section class=\"card\">\n<h2>Tokens</h2>\n<dl class=\"meta\">\n");
    meta(h, "output", fmt::count(t.output));
    meta(h, "thinking", fmt::count(t.thinking));
    meta(h, "input", fmt::count(t.input));
    meta(h, "cache read", fmt::count(t.cache_read));
    meta(h, "cache write", fmt::count(t.cache_write));
    h.push_str("</dl>\n</section>\n");
}

/// Where the user was in the loop — the part a tool histogram cannot show.
fn involvement(h: &mut String, s: &Summary) {
    h.push_str("<section class=\"card\">\n<h2>User involvement</h2>\n");
    if s.user_involvement.is_empty() {
        h.push_str(
            "<p class=\"note\">The user did not speak after the opening prompt — this \
             session ran unattended.</p>\n</section>\n",
        );
        return;
    }
    h.push_str(&format!(
        "<p class=\"note\">{} prompt(s), {} question(s) asked, {} pasted \
         image(s)/document(s).</p>\n",
        s.user_prompts, s.ask_user_questions, s.pasted_attachments
    ));
    h.push_str("<ol class=\"turns\">\n");
    for item in &s.user_involvement {
        let when = item.at().map(|t| clock(&t)).unwrap_or_default();
        match item {
            Involvement::Prompt {
                preview,
                truncated,
                attachments,
                ..
            } => {
                h.push_str(&format!(
                    "<li class=\"prompt\"><span class=\"when\">{}</span>\
                     <span class=\"what\">{}{}{}</span></li>\n",
                    esc(&when),
                    esc(&label_of(preview)),
                    if *truncated { "…" } else { "" },
                    match attachments {
                        0 => String::new(),
                        n => format!(" <span class=\"chip\">+{n} attached</span>"),
                    },
                ));
            }
            Involvement::Question {
                header,
                question,
                options,
                chosen,
                ..
            } => {
                h.push_str(&format!(
                    "<li class=\"ask\"><span class=\"when\">{}</span><span class=\"what\">",
                    esc(&when)
                ));
                if let Some(head) = header {
                    h.push_str(&format!("<span class=\"chip\">{}</span> ", esc(head)));
                }
                h.push_str(&format!("{}<br>", esc(question)));
                match chosen {
                    Some(answer) => h.push_str(&format!(
                        "<span class=\"chose\">chose: {}</span>",
                        esc(answer)
                    )),
                    None => h.push_str("<span class=\"chose none\">no answer recorded</span>"),
                }
                if !options.is_empty() {
                    h.push_str(&format!(
                        " <span class=\"opts\">of {}</span>",
                        esc(&options.join(" · "))
                    ));
                }
                h.push_str("</span></li>\n");
            }
        }
    }
    h.push_str("</ol>\n</section>\n");
}

fn delegation(h: &mut String, s: &Summary) {
    if s.skills.is_empty() && s.subagents.is_empty() {
        return;
    }
    h.push_str("<section class=\"card\">\n<h2>Skills &amp; delegation</h2>\n<p>");
    for skill in &s.skills {
        h.push_str(&format!("<span class=\"chip\">/{}</span> ", esc(skill)));
    }
    for agent in &s.subagents {
        h.push_str(&format!(
            "<span class=\"chip agent\">{}</span> ",
            esc(agent)
        ));
    }
    h.push_str("</p>\n");
    if s.subagent_transcripts > 0 {
        h.push_str(&format!(
            "<p class=\"note unknown\">{} subagent transcript(s) sit beside this session and \
             are <strong>not</strong> folded into the numbers above.</p>\n",
            s.subagent_transcripts
        ));
    }
    h.push_str("</section>\n");
}

fn meta(h: &mut String, key: &str, value: impl AsRef<str>) {
    let value = value.as_ref();
    if value.is_empty() {
        return;
    }
    h.push_str(&format!(
        "<dt>{}</dt><dd>{}</dd>\n",
        esc(key),
        esc(value.trim())
    ));
}

fn stat(h: &mut String, key: &str, value: &str, note: &str) {
    h.push_str(&format!(
        "<div class=\"stat\"><span class=\"k\">{}</span><span class=\"v\">{}</span>\
         <span class=\"n\">{}</span></div>\n",
        esc(key),
        esc(value),
        esc(note)
    ));
}

fn join(items: impl Iterator<Item = String>) -> String {
    items.collect::<Vec<_>>().join(", ")
}

fn stamp(t: &DateTime<Utc>) -> String {
    t.to_rfc3339_opts(SecondsFormat::Secs, true)
}

fn clock(t: &DateTime<Utc>) -> String {
    t.format("%m-%d %H:%M:%S").to_string()
}

/// Escape for both element text and double-quoted attributes.
///
/// Tool output and prompt text go straight onto the page, and both routinely
/// contain angle brackets and quotes.
fn esc(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const CSS: &str = r#"
:root{
  --bg:#faf9f7; --panel:#fff; --ink:#1b1a18; --muted:#6d6a63; --line:#e4e0d9;
  --accent:#35618f; --bar:#7ea3c9; --fail:#b8412f; --add:#2f7d4f; --del:#b8412f;
  --user:#4a7c4e; --ask:#a06a1f; --warnbg:#fdf3e6; --chip:#efece6;
}
@media (prefers-color-scheme: dark){
  :root{
    --bg:#16181a; --panel:#1e2124; --ink:#e6e3dd; --muted:#9a958c; --line:#2f3439;
    --accent:#7fb0e0; --bar:#5b87b5; --fail:#e07a63; --add:#68b884; --del:#e07a63;
    --user:#7cb87f; --ask:#d9a34e; --warnbg:#2c2519; --chip:#2a2e33;
  }
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
  font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
main{max-width:1000px;margin:0 auto;padding:32px 20px 64px}
h1{font-size:24px;margin:0 0 12px;letter-spacing:-.01em}
h2{font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);
  margin:0 0 12px;font-weight:600}
header{border-bottom:1px solid var(--line);padding-bottom:20px;margin-bottom:20px}
dl.meta{display:grid;grid-template-columns:auto 1fr;gap:2px 14px;margin:0;font-size:13px}
dl.meta dt{color:var(--muted)}
dl.meta dd{margin:0;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  overflow-wrap:anywhere}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;
  padding:16px 18px;margin-bottom:16px}
.cols{display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap}
.cols>*{flex:1 1 320px;min-width:0}
.col{margin-bottom:0}
.cols .card{margin-bottom:16px}
.stats{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:16px}
.stat{flex:1 1 140px;background:var(--panel);border:1px solid var(--line);border-radius:10px;
  padding:12px 14px;display:flex;flex-direction:column;gap:2px}
.stat .k{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
.stat .v{font-size:26px;font-weight:600;letter-spacing:-.02em}
.stat .n{font-size:12px;color:var(--muted)}
.note{font-size:12.5px;color:var(--muted);margin:0 0 10px}
.note.unknown{border-left:3px solid var(--ask);padding-left:9px;margin-top:10px}
.warn{background:var(--warnbg);border:1px solid var(--ask);border-radius:8px;
  padding:10px 14px;font-size:13px;margin:0 0 16px}
.big{font-size:22px;font-weight:600;margin:0}
.add{color:var(--add)} .del{color:var(--del)}

/* time strip */
.strip{display:flex;align-items:stretch;gap:0;border:1px solid var(--line);
  border-radius:8px;overflow-x:auto;overflow-y:hidden;background:var(--bg)}
.span{display:flex;flex-direction:column;min-width:0;flex-shrink:1;flex-basis:0}
.cols-b{display:flex;align-items:flex-end;height:96px;padding:0 1px}
/* Columns fill the width when the session fits, floor at 2px when it does not
   and let the strip scroll — squashing a busy session to nothing would be a
   quieter lie than making the reader scroll. */
.col-b{flex:1 1 0;min-width:2px;display:flex;flex-direction:column;justify-content:flex-end;
  height:100%;padding:0 .5px}
.col-b .mk{display:block;height:7px;margin-bottom:2px;border-radius:2px}
.mk.mkuser{background:var(--user)}
.mk.mkask{background:var(--ask)}
.track{flex:1;display:flex;align-items:flex-end}
.col-b .bar{width:100%;background:var(--bar);border-radius:1px 1px 0 0;min-height:1px}
.col-b .bar.fail{background:var(--fail)}
.axis{display:flex;justify-content:space-between;font-size:10.5px;color:var(--muted);
  padding:4px 3px 2px;border-top:1px solid var(--line);gap:6px;white-space:nowrap;overflow:hidden}
.gap{display:flex;align-items:center;justify-content:center;
  background:repeating-linear-gradient(135deg,transparent 0 4px,var(--line) 4px 5px);
  border-left:1px dashed var(--line);border-right:1px dashed var(--line)}
.strip.roomy .gap{flex:0 0 32px}
.strip.dense .gap{flex:0 0 6px}
.gap span{font-size:10px;color:var(--muted);background:var(--panel);padding:1px 3px;
  border-radius:3px;transform:rotate(-90deg);white-space:nowrap}
.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:11.5px;color:var(--muted);
  margin:10px 0 0;align-items:center}
.key{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;
  vertical-align:-1px}
.key.bar{background:var(--bar)} .key.barfail{background:var(--fail)}
.key.mkuser{background:var(--user)} .key.mkask{background:var(--ask)}
.key.gapkey{background:repeating-linear-gradient(135deg,transparent 0 3px,var(--line) 3px 4px);
  border:1px solid var(--line)}

/* tool bars */
ul.bars{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:5px}
ul.bars li{display:grid;grid-template-columns:minmax(0,140px) 1fr auto;gap:10px;
  align-items:center;font-size:13px}
ul.bars .name{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
ul.bars .track{height:9px;background:var(--chip);border-radius:5px;overflow:hidden;display:flex}
ul.bars .fill{background:var(--bar);height:100%}
ul.bars .fill.fail{background:var(--fail)}
ul.bars .n{color:var(--muted);font-variant-numeric:tabular-nums;font-size:12px;white-space:nowrap}
ul.bars em{color:var(--fail);font-style:normal}

/* involvement */
ol.turns{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:0}
ol.turns li{display:grid;grid-template-columns:auto 1fr;gap:12px;padding:7px 0 7px 11px;
  border-left:3px solid var(--line);font-size:13.5px}
ol.turns li.prompt{border-left-color:var(--user)}
ol.turns li.ask{border-left-color:var(--ask)}
ol.turns .when{color:var(--muted);font-size:11.5px;font-variant-numeric:tabular-nums;
  padding-top:2px;white-space:nowrap}
ol.turns .what{min-width:0;overflow-wrap:anywhere}
.chose{color:var(--accent);font-weight:600;font-size:12.5px}
.chose.none{color:var(--muted);font-weight:400;font-style:italic}
.opts{color:var(--muted);font-size:11.5px}
.chip{display:inline-block;background:var(--chip);border-radius:4px;padding:1px 6px;
  font-size:11.5px;color:var(--muted);white-space:nowrap}
.chip.agent{color:var(--accent)}
code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.92em}
footer{color:var(--muted);font-size:11.5px;border-top:1px solid var(--line);
  padding-top:14px;margin-top:24px}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::summary::{Summary, summarize};
    use crate::transcript::Transcript;

    fn render_lines(lines: &[&str]) -> String {
        let t = Transcript {
            records: lines
                .iter()
                .map(|l| serde_json::from_str(l).unwrap())
                .collect(),
            skipped: 0,
        };
        report(&summarize(None, &t))
    }

    /// The facts JSON is a contract, and the renderer is its first consumer:
    /// a report built from a *serialized* facts document must be identical to
    /// one built from the summary in memory. If this drifts, the seam a future
    /// front-end plugs into has quietly stopped being real.
    #[test]
    fn a_report_from_serialized_facts_is_identical() {
        let t = Transcript {
            records: [
                r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                    "content":"start"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T10:00:20.000Z","message":{
                    "model":"claude-opus-5","usage":{"output_tokens":40},
                    "content":[{"type":"tool_use","id":"t1","name":"AskUserQuestion","input":{
                        "questions":[{"question":"Now?","header":"When",
                        "options":[{"label":"Yes"}]}]}}]}}"#,
                r#"{"type":"user","timestamp":"2026-08-20T10:04:00.000Z","message":{"content":[
                    {"type":"tool_result","tool_use_id":"t1","is_error":true}]},
                    "toolUseResult":{"answers":{"Now?":"Yes"}}}"#,
            ]
            .iter()
            .map(|l| serde_json::from_str(l).unwrap())
            .collect(),
            skipped: 0,
        };
        let direct = summarize(None, &t);
        let json = serde_json::to_string(&direct).unwrap();
        let round_tripped: Summary = serde_json::from_str(&json).unwrap();
        assert_eq!(report(&direct), report(&round_tripped));
        // the parts a shallow round trip would lose: the tagged involvement
        // enum, and the activity series it is positioned against
        let html = report(&round_tripped);
        assert!(html.contains("chose: Yes"), "answer lost in the round trip");
        assert!(
            html.contains("3m idle"),
            "idle break lost in the round trip"
        );
        assert_eq!(round_tripped.activity.spans.len(), 2);
        assert_eq!(round_tripped.tokens.output, 40);
    }

    /// No network, ever. The assertions name the constructs that actually
    /// *fetch*, not the substring "https://" — a session where the user pasted
    /// a URL puts that text on the page as escaped prose, which reaches
    /// nothing. Confusing the two would make this test fire on real sessions
    /// and teach the next person to weaken it.
    #[test]
    fn the_report_is_self_contained() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"go, see https://example.invalid/spec"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:30.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Read"}]}}"#,
        ]);
        assert!(html.starts_with("<!doctype html>"));
        for probe in [
            "<script", "<link", "<img", "<iframe", "<object", "<embed", "src=", "@import", "url(",
        ] {
            assert!(!html.contains(probe), "report can fetch: {probe}");
        }
        // The pasted URL is still on the page — as text, which is the point.
        assert!(html.contains("https://example.invalid/spec"));
    }

    #[test]
    fn prompt_text_is_escaped_rather_than_injected() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"fix <img onerror=x> & \"quotes\""}}"#,
        ]);
        assert!(html.contains("fix &lt;img onerror=x&gt; &amp; &quot;quotes&quot;"));
        assert!(!html.contains("<img onerror"));
    }

    #[test]
    fn an_opaque_edit_is_reported_as_unknown_not_as_zero() {
        let html = render_lines(&[
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Bash"}]}}"#,
        ]);
        assert!(html.contains("recoverable diff"));
        assert!(html.contains("an unknown, not a zero"));
    }

    #[test]
    fn idle_is_drawn_as_a_collapsed_break() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z"}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:30.000Z"}"#,
            r#"{"type":"user","timestamp":"2026-08-20T12:00:30.000Z"}"#,
        ]);
        assert!(html.contains(r#"class="gap" title="2h00m idle""#));
    }

    #[test]
    fn a_question_shows_what_was_asked_and_chosen() {
        let html = render_lines(&[
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"AskUserQuestion","input":{
                    "questions":[{"question":"Which store?","header":"Store",
                    "options":[{"label":"Postgres"},{"label":"SQLite"}]}]}}]}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:20.000Z","message":{"content":[
                {"type":"tool_result","tool_use_id":"t1"}]},
                "toolUseResult":{"answers":{"Which store?":"SQLite"}}}"#,
        ]);
        assert!(html.contains("Which store?"));
        assert!(html.contains("chose: SQLite"));
        assert!(html.contains("Postgres · SQLite"));
    }
}
