//! The static report: facts in, one self-contained HTML file out.
//!
//! Renders from [`Summary`] alone — never from the transcript — so the
//! extractor/renderer seam stays honest and `kagviz show <id> --json` output
//! is a valid input. Nothing here computes a number; if a value is not already
//! in the facts, it does not appear on the page.
//!
//! Self-contained is a hard requirement, not a preference: no external fonts,
//! stylesheets, scripts or images, so the file still renders correctly with no
//! network in five years, and can be mailed or archived as one artifact.

use crate::fmt;
use crate::label;
use crate::summary::{ActivitySpan, Bucket, Involvement, Phase, Summary};
use chrono::{DateTime, SecondsFormat, Utc};
use std::collections::BTreeMap;

/// Render the whole report.
pub fn report(s: &Summary) -> String {
    let mut h = String::with_capacity(32 * 1024);
    h.push_str("<!doctype html>\n<html lang=\"en\">\n<head>\n");
    h.push_str("<meta charset=\"utf-8\">\n");
    h.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    h.push_str(&format!("<title>{}</title>\n", esc(&title(s))));
    h.push_str("<style>\n");
    h.push_str(CSS);
    h.push_str("</style>\n</head>\n<body>\n<main>\n");

    header(&mut h, s);
    if s.skipped_lines > 0 {
        h.push_str(&format!(
            "<p class=\"warn\">{} transcript line(s) did not parse. Every number below is \
             a partial reading.</p>\n",
            s.skipped_lines
        ));
    }
    written(&mut h, s);
    headline(&mut h, s);
    time_strip(&mut h, s);
    phases_section(&mut h, s);
    // Three siblings, not a nested column: the grid decides how many fit, so
    // a wide screen gets three across instead of one card and a lot of nothing.
    h.push_str("<div class=\"cols\">\n");
    tool_mix(&mut h, s);
    file_changes(&mut h, s);
    tokens(&mut h, s);
    h.push_str("</div>\n");
    involvement(&mut h, s);
    delegation(&mut h, s);

    h.push_str("<footer>Generated by kagviz. ");
    // The old footer said "nothing here is inferred", which stops being true
    // the moment a headline is on the page. It has to say which parts are
    // which rather than keep a claim that is now half wrong.
    match &s.labels {
        Some(l) => h.push_str(&format!(
            "Every <em>figure</em> is computed from the transcript. The text marked \
             <em>written</em> — the headline and the phase labels — was written by {} \
             over those figures, and is the only thing here that was not measured. ",
            esc(&label::attribution(l)),
        )),
        None => {
            h.push_str("Every figure is computed from the transcript; nothing here is inferred. ")
        }
    }
    h.push_str("Times are UTC.</footer>\n");
    h.push_str("</main>\n</body>\n</html>\n");
    h
}

fn title(s: &Summary) -> String {
    let project = s.project.as_deref().unwrap_or("session");
    match &s.started {
        Some(t) => format!("{project} — {}", t.format("%Y-%m-%d")),
        None => project.to_string(),
    }
}

fn header(h: &mut String, s: &Summary) {
    h.push_str("<header>\n");
    h.push_str(&format!("<h1>{}</h1>\n", esc(&title(s))));
    h.push_str("<dl class=\"meta\">\n");
    meta(h, "session", s.session_id.as_deref().unwrap_or_default());
    meta(h, "cwd", s.cwd.as_deref().unwrap_or_default());
    meta(h, "branch", s.git_branch.as_deref().unwrap_or_default());
    meta(h, "cli", join(s.cli_versions.iter().cloned()));
    meta(h, "models", join(s.models.keys().cloned()));
    meta(
        h,
        "window",
        match (&s.started, &s.ended) {
            (Some(a), Some(b)) => format!("{} → {}", stamp(a), stamp(b)),
            _ => String::new(),
        },
    );
    h.push_str("</dl>\n</header>\n");
}

/// The model-written headline — the only prose on this page nobody counted.
///
/// It sits above the numbers because that is where a reader starts, and it is
/// styled so it can never be mistaken for one of them: no `.stat` card, no
/// large numeral, an accent rule down the side, and an attribution naming the
/// model in the block itself rather than only in the footer. A reader who
/// cannot tell the sentence from the counts has been handed exactly the
/// confusion this project exists to avoid.
///
/// Absent when there are no labels — which is the default path, so the page
/// below has to look finished without it, not broken.
fn written(h: &mut String, s: &Summary) {
    let Some(l) = &s.labels else {
        return;
    };
    h.push_str("<section class=\"written\">\n");
    h.push_str(&format!("<p class=\"said\">{}</p>\n", esc(&l.headline)));
    h.push_str(&format!(
        "<p class=\"by\"><span class=\"mark\">written</span> by {} over the facts below. \
         It and the marked phase labels are the only text here that was not \
         measured.</p>\n",
        esc(&label::attribution(l)),
    ));
    h.push_str("</section>\n");
}

/// The four numbers that answer "how did this go" at a glance.
///
/// Active time is the headline and wall clock is its sub-label rather than its
/// peer. Both have to be on the page — active alone is dishonest about a
/// session resumed over three days, which is why `transcript-format.md` trap #2
/// exists — but equal billing put the eye on the bigger, less meaningful
/// number. Wall reads as the context for active, which is what it is.
fn headline(h: &mut String, s: &Summary) {
    let failures = s.total_tool_failures();
    h.push_str("<section class=\"stats\">\n");
    stat(
        h,
        "active",
        &fmt::duration(s.active_secs),
        &format!(
            "over {} wall · {} idle",
            fmt::duration(s.wall_secs),
            fmt::duration(s.idle_secs)
        ),
    );
    if let Some(dominant) = s.dominant_phase() {
        stat(
            h,
            "phases",
            &s.phases.len().to_string(),
            &format!("mostly {}", dominant.label()),
        );
    }
    stat(
        h,
        "turns",
        &s.assistant_turns.to_string(),
        &format!("{} user prompt(s)", s.user_prompts),
    );
    // The count says nothing without its denominator beside it — 45 failed of
    // 2,777 is a different session from 45 of 90 — so the rate follows it on
    // the same line. `tool_failure_rate` owns the denominator decision and
    // the `<unknown>` guard; the zero case stays bare.
    let failed = match (failures, s.tool_failure_rate()) {
        (0, _) => "none failed".to_string(),
        (n, Some(rate)) => format!("{n} failed · {}", fmt::percent(rate)),
        (n, None) => format!("{n} failed"),
    };
    // Delegated calls are named right here rather than only in the tier
    // below. A session that spawned three agents shows three `Agent` calls in
    // this number, and a reader who stops at the headline should still learn
    // that most of the work happened somewhere else.
    let delegated = s.delegation.totals.tool_calls.values().sum::<u32>();
    let note = if delegated > 0 {
        format!("{failed} · {} more delegated", delegated)
    } else {
        failed
    };
    stat(h, "tools", &s.total_tool_calls().to_string(), &note);
    h.push_str("</section>\n");
}

/// The time strip: uniformly-scaled buckets, with idle collapsed to a labelled
/// break rather than stretched across the page.
fn time_strip(h: &mut String, s: &Summary) {
    let a = &s.activity;
    if a.spans.is_empty() {
        return;
    }
    let peak = a.peak_records().max(1);
    let marks = marks_by_bucket(s);

    h.push_str("<section class=\"card\">\n<h2>Time</h2>\n");
    h.push_str(&format!(
        "<p class=\"note\">{} of work in {} stretch(es), {} per column. Idle gaps of \
         {}+ are collapsed to a break.</p>\n",
        fmt::duration(s.active_secs),
        a.spans.len(),
        fmt::duration(a.bucket_secs),
        fmt::duration(crate::summary::IDLE_GAP_SECS),
    ));
    // The band above the columns names its phase in words only where there is
    // room for the word. On a session with hundreds of stretches there never
    // is, so say plainly what carries the kind instead — otherwise a reader
    // meets a row of colours with no key on the card they are looking at.
    if !s.phases.is_empty() {
        h.push_str(
            "<p class=\"note\">Band colours name the phase kind — the Phases card below \
             is the key, and every band names itself on hover.</p>\n",
        );
    }
    // Break labels need room to sit in; past a dozen stretches there is none,
    // and the durations live in the tooltips instead.
    let roomy = a.spans.len() <= LABELLED_BREAKS_MAX;
    // ...and past sixty, the fixed-width breaks themselves start eating the
    // strip. On the corpus's 209-span session, 208 breaks at 6px each claimed
    // 1248px while the work columns were squeezed onto their 2px floor: the
    // panel that exists to collapse idle was rendering 72% idle. A break only
    // has to be *visible*, not proportional — its duration is deliberately not
    // to scale — so above this many it narrows and gives the width back.
    let class = match a.spans.len() {
        n if n <= LABELLED_BREAKS_MAX => "roomy",
        n if n <= NARROW_BREAKS_MIN => "dense",
        _ => "packed",
    };
    // Past a few hundred columns no CSS constant reaches the strip: it is a
    // wall of 2px bars, and the fix is a zoom (#1591 — the real one lands in
    // the front-end). Until then, a checkbox: CSS `:checked` alone, no
    // script, so the report stays self-contained. Checked, every column takes
    // a fixed readable width and the strip scrolls sideways. It only ever
    // widens, so below the threshold it would change nothing and is not
    // offered — the control precedes the strip as its *sibling*, which is the
    // whole mechanism (`~`), so it cannot live inside a `<p>`.
    let buckets: usize = a.spans.iter().map(|sp| sp.buckets.len()).sum();
    if buckets >= ZOOM_MIN_BUCKETS {
        h.push_str(
            "<input type=\"checkbox\" id=\"zoom\" class=\"zoom\">\
             <label class=\"zoomctl\" for=\"zoom\">zoom in<span> — every column at a \
             readable width; the strip scrolls sideways</span></label>\n",
        );
    }
    h.push_str(&format!("<div class=\"strip {class}\">\n"));

    for (si, span) in a.spans.iter().enumerate() {
        if span.idle_before_secs > 0 {
            let label = fmt::duration(span.idle_before_secs);
            h.push_str(&format!(
                "<div class=\"gap\" title=\"{} idle\">",
                esc(&label)
            ));
            if roomy {
                h.push_str(&format!("<span>{}</span>", esc(&label)));
            }
            h.push_str("</div>\n");
        }
        h.push_str(&format!(
            "<div class=\"span\" style=\"flex-grow:{}\">\n",
            span.buckets.len()
        ));
        phase_bands(h, s, si, span);
        h.push_str("<div class=\"cols-b\">\n");
        for (bi, bucket) in span.buckets.iter().enumerate() {
            let at = span.started + chrono::Duration::seconds(bi as i64 * a.bucket_secs);
            let mark = marks.get(&(si, bi));
            column(h, bucket, peak, &at, mark);
        }
        h.push_str("</div>\n<div class=\"axis\">");
        h.push_str(&format!(
            "<span>{}</span><span>{}</span>",
            esc(&clock(&span.started)),
            esc(&fmt::duration(span.secs))
        ));
        h.push_str("</div>\n</div>\n");
    }

    h.push_str("</div>\n");
    h.push_str(
        "<p class=\"legend\"><span class=\"key bar\"></span>work \
         <span class=\"key barfail\"></span>tool failure \
         <span class=\"key mkuser\"></span>user prompt \
         <span class=\"key mkask\"></span>question asked \
         <span class=\"key gapkey\"></span>idle, collapsed</p>\n",
    );
    h.push_str("</section>\n");
}

/// Above this many stretches of work there is no room to label the breaks.
const LABELLED_BREAKS_MAX: usize = 12;
/// Above this many, the breaks narrow so the work columns keep the width.
/// Sixty 6px breaks is about 350px — a quarter of a typical strip, and the
/// most idle should ever take on a panel whose job is collapsing it.
///
/// Narrowing further is not the answer, and this is the place someone would
/// try it. Past a few hundred stretches the breaks are noise however thin they
/// are, and that is the same density at which the whole strip stops being
/// legible — the fix there is zooming it (#1591), not shaving pixels here.
const NARROW_BREAKS_MIN: usize = 60;

/// Columns at or above which the strip offers the zoom-in checkbox.
///
/// The zoom sets each column to [`ZOOM_COLUMN_PX`]; at the layout's full
/// width — 1480px less the page and card padding, about 1,400px of strip —
/// that is room for roughly 116 columns before the flex share squeezes them
/// narrower. Below that count the zoom would change nothing at full width,
/// and a control that does nothing is worse than one that arrives a little
/// late on a half-width window. Ken's goldilocks reference (img-639 on
/// #1591) is a 118-column strip filling exactly that width, which is where
/// the number comes from. Across the corpus it offers the box on about
/// 250 of 400 sessions: `MAX_BUCKETS` is 240, so anything over an hour or two
/// saturates the strip.
const ZOOM_MIN_BUCKETS: usize = 120;

/// Column width, in CSS pixels, that the zoom sets — the density of the
/// reference snip (11–12px). Spelled in the `.zoom:checked` rule in [`CSS`]
/// and mirrored here for the doc comment; the zoom test holds the two in step.
#[allow(
    dead_code,
    reason = "read by that test; the stylesheet is the real use"
)]
const ZOOM_COLUMN_PX: u32 = 12;

/// The band width, in CSS pixels, at which a phase label is worth drawing.
///
/// Sized for the *longest* label — `implementing`, twelve characters at 9.5px
/// plus its padding — so a label that is shown is never a clipped one. A
/// narrower band keeps its colour and its tooltip, and loses only the
/// fragment that was unreadable anyway.
///
/// Unlike the two above, this one cannot be applied here: a band's width is
/// not a fact about the session, it is what the browser works out from the
/// flex share, the window and the 2px column floor. The number is therefore
/// spelled in the `@container` rule in [`CSS`] and mirrored here for the doc
/// comment; `a_band_too_narrow_for_its_label_shows_colour_and_tooltip_instead`
/// holds the two in step.
#[allow(
    dead_code,
    reason = "read by that test; the stylesheet is the real use"
)]
const BAND_LABEL_MIN_PX: u32 = 64;

/// The phase band over one span's columns.
///
/// A bucket belongs to whichever phase was running when it opened. At a wide
/// bucket width several phases can fall inside one column and only the first
/// gets drawn — [`phases_section`] reports how many that cost, because a
/// silently dropped phase would read as a phase that never happened.
fn phase_bands(h: &mut String, s: &Summary, si: usize, span: &ActivitySpan) {
    let runs = bands_for_span(s, si, span);
    if runs.is_empty() {
        return;
    }
    h.push_str("<div class=\"bands\">");
    for (pi, columns) in runs {
        let p = &s.phases[pi];
        h.push_str(&format!(
            "<div class=\"band ph-{}\" style=\"flex-grow:{columns}\" title=\"{}\">\
             <span>{}</span></div>",
            p.kind.label(),
            esc(&phase_tip(p)),
            esc(p.kind.label()),
        ));
    }
    h.push_str("</div>\n");
}

/// Runs of `(phase index, columns)` covering a span's buckets, left to right.
fn bands_for_span(s: &Summary, si: usize, span: &ActivitySpan) -> Vec<(usize, usize)> {
    let width = s.activity.bucket_secs.max(1);
    let here: Vec<usize> = (0..s.phases.len())
        .filter(|&i| s.phases[i].span == si)
        .collect();
    if here.is_empty() {
        return Vec::new();
    }
    let mut runs: Vec<(usize, usize)> = Vec::new();
    let mut cur = 0;
    for bi in 0..span.buckets.len() {
        let at = span.started + chrono::Duration::seconds(bi as i64 * width);
        while cur + 1 < here.len() && s.phases[here[cur + 1]].started <= at {
            cur += 1;
        }
        match runs.last_mut() {
            Some((last, columns)) if *last == here[cur] => *columns += 1,
            _ => runs.push((here[cur], 1)),
        }
    }
    runs
}

/// How many phases the strip could not give a column of its own.
fn phases_without_a_band(s: &Summary) -> usize {
    let drawn: usize = s
        .activity
        .spans
        .iter()
        .enumerate()
        .map(|(si, span)| bands_for_span(s, si, span).len())
        .sum();
    s.phases.len().saturating_sub(drawn)
}

fn phase_tip(p: &Phase) -> String {
    let mut tip = format!(
        "{} · {} · {}",
        p.kind.label(),
        clock(&p.started),
        fmt::duration(p.secs)
    );
    if p.tool_calls > 0 {
        tip.push_str(&format!(" · {} tool call(s)", p.tool_calls));
    }
    if p.tool_failures > 0 {
        tip.push_str(&format!(", {} failed", p.tool_failures));
    }
    if let Some(opened) = &p.opened_by {
        tip.push_str(" — ");
        tip.push_str(&label_of(opened));
    }
    tip
}

fn mix_line(p: &Phase) -> String {
    p.mix
        .parts()
        .iter()
        .map(|(name, n)| format!("{name} {n}"))
        .collect::<Vec<_>>()
        .join(" · ")
}

/// Past this many phases the ordered list stops being readable and the
/// longest ones are shown instead. The count that was dropped is always said.
const PHASE_LIST_MAX: usize = 30;
const PHASE_LIST_LONGEST: usize = 15;

/// Where the time went, by phase.
///
/// The rollup comes first because it is the answer most sessions want; the
/// ordered list is the narrative under it. Neither invents a name — every
/// label here is the mechanical one the facts carry.
fn phases_section(h: &mut String, s: &Summary) {
    if s.phases.is_empty() {
        return;
    }
    h.push_str("<section class=\"card\">\n<h2>Phases</h2>\n");
    h.push_str(&format!(
        "<p class=\"note\">{} phase(s), cut at every user turn and at every idle break. \
         A phase never spans a gap, and the phases in one stretch of work account for \
         all of it. Labels name the tool mix, not the intent.</p>\n",
        s.phases.len()
    ));

    let rollup = s.phase_rollup();
    let peak = rollup.first().map_or(1, |(_, _, secs)| (*secs).max(1));
    h.push_str("<ul class=\"bars\">\n");
    for (kind, n, secs) in &rollup {
        h.push_str(&format!(
            "<li><span class=\"name\">{}</span>\
             <span class=\"track\">\
             <span class=\"fill ph-{}\" style=\"width:{:.3}%\"></span>\
             </span><span class=\"n\">{} · {n} phase(s)</span></li>\n",
            esc(kind.label()),
            kind.label(),
            *secs as f64 * 100.0 / peak as f64,
            esc(&fmt::duration(*secs)),
        ));
    }
    h.push_str("</ul>\n");

    // Carry the index: a written label is keyed by position in the facts'
    // `phases`, and this list sorts and truncates.
    let mut shown: Vec<(usize, &Phase)> = s.phases.iter().enumerate().collect();
    let omitted = if shown.len() > PHASE_LIST_MAX {
        shown.sort_by(|a, b| b.1.secs.cmp(&a.1.secs).then(a.1.started.cmp(&b.1.started)));
        shown.truncate(PHASE_LIST_LONGEST);
        shown.sort_by_key(|(_, p)| p.started);
        s.phases.len() - PHASE_LIST_LONGEST
    } else {
        0
    };
    if omitted > 0 {
        h.push_str(&format!(
            "<p class=\"note\">Listing the {PHASE_LIST_LONGEST} longest; {omitted} shorter \
             phase(s) are not shown. The band on the strip above is the full sequence.</p>\n"
        ));
    }

    h.push_str("<ol class=\"turns phases\">\n");
    for (i, p) in shown {
        h.push_str(&format!(
            "<li class=\"ph-{}\"><span class=\"when\">{}</span><span class=\"what\">\
             <span class=\"chip kind\">{}</span> <strong>{}</strong>",
            p.kind.label(),
            esc(&clock(&p.started)),
            esc(p.kind.label()),
            esc(&fmt::duration(p.secs)),
        ));
        match &p.opened_by {
            Some(opened) => h.push_str(&format!(" — {}", esc(&label_of(opened)))),
            None => h.push_str(" — <em class=\"resumed\">resumed, nothing said</em>"),
        }
        // Beside the mechanical kind, never in place of it: `implementing` is
        // what the tool mix says, and the written label is what a model made
        // of it. Both, marked, or the reader cannot audit either.
        if let Some(written) = s.labels.as_ref().and_then(|l| l.phase(i)) {
            h.push_str(&format!(
                " <span class=\"chip said\">{}</span>",
                esc(written)
            ));
        }
        let mix = mix_line(p);
        if !mix.is_empty() {
            h.push_str(&format!("<br><span class=\"opts\">{}</span>", esc(&mix)));
        }
        h.push_str("</span></li>\n");
    }
    h.push_str("</ol>\n");

    let unbanded = phases_without_a_band(s);
    if unbanded > 0 {
        h.push_str(&format!(
            "<p class=\"note unknown\">{unbanded} phase(s) are shorter than one column at \
             this scale and carry no band on the strip. They are counted here — the strip \
             cannot draw them, which is not the same as their not existing.</p>\n"
        ));
    }
    h.push_str("</section>\n");
}

fn column(h: &mut String, b: &Bucket, peak: u32, at: &DateTime<Utc>, mark: Option<&Mark>) {
    let pct = if b.is_empty() {
        0
    } else {
        (6 + (b.records * 94).div_ceil(peak)).min(100)
    };
    let mut tip = format!("{} · {} record(s)", clock(at), b.records);
    if b.tool_calls > 0 {
        tip.push_str(&format!(", {} tool call(s)", b.tool_calls));
    }
    if b.tool_failures > 0 {
        tip.push_str(&format!(", {} failed", b.tool_failures));
    }
    if b.output_tokens > 0 {
        tip.push_str(&format!(", {} out", fmt::count(b.output_tokens)));
    }
    if let Some(m) = mark {
        tip.push_str(" — ");
        tip.push_str(&m.tip);
    }

    let class = if b.tool_failures > 0 {
        "bar fail"
    } else {
        "bar"
    };
    h.push_str(&format!("<div class=\"col-b\" title=\"{}\">", esc(&tip)));
    match mark {
        Some(m) => h.push_str(&format!("<i class=\"mk {}\"></i>", m.class)),
        None => h.push_str("<i class=\"mk\"></i>"),
    }
    h.push_str(&format!(
        "<div class=\"track\"><div class=\"{class}\" style=\"height:{pct}%\"></div></div></div>\n"
    ));
}

/// A user-involvement marker sitting over one bucket of the strip.
struct Mark {
    class: &'static str,
    tip: String,
}

/// Map each involvement moment onto the bucket that holds it.
///
/// A moment outside every span cannot happen — spans are built from the same
/// timestamps — but one without a timestamp is simply not placed.
fn marks_by_bucket(s: &Summary) -> BTreeMap<(usize, usize), Mark> {
    let mut out: BTreeMap<(usize, usize), Mark> = BTreeMap::new();
    let width = s.activity.bucket_secs.max(1);

    for item in &s.user_involvement {
        let Some(at) = item.at() else { continue };
        let Some((si, span)) = s
            .activity
            .spans
            .iter()
            .enumerate()
            .find(|(_, sp)| at >= sp.started && at <= sp.ended)
        else {
            continue;
        };
        let bi = (((at - span.started).num_seconds() / width) as usize).min(span.buckets.len() - 1);
        let (class, tip) = match item {
            Involvement::Prompt { preview, .. } => ("mkuser", label_of(preview)),
            Involvement::Question { question, .. } => ("mkask", format!("asked: {question}")),
        };
        out.entry((si, bi))
            .and_modify(|m| {
                m.tip.push_str(" / ");
                m.tip.push_str(&tip);
            })
            .or_insert(Mark { class, tip });
    }
    out
}

fn label_of(preview: &str) -> String {
    if preview.is_empty() {
        "user pasted an attachment".to_string()
    } else {
        preview.to_string()
    }
}

fn tool_mix(h: &mut String, s: &Summary) {
    h.push_str("<section class=\"card wide\">\n<h2>Tools</h2>\n");
    if s.tool_calls.is_empty() {
        h.push_str("<p class=\"note\">No tool calls in this session.</p>\n</section>\n");
        return;
    }
    let peak = s.tool_calls.values().copied().max().unwrap_or(1).max(1);
    let mut rows: Vec<(&String, &u32)> = s.tool_calls.iter().collect();
    rows.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));

    h.push_str("<ul class=\"bars\">\n");
    for (name, n) in rows {
        let failed = s.tool_failures.get(name).copied().unwrap_or(0);
        let ok = n.saturating_sub(failed);
        h.push_str(&format!(
            "<li><span class=\"name\">{}</span>\
             <span class=\"track\">\
             <span class=\"fill\" style=\"width:{:.3}%\"></span>\
             <span class=\"fill fail\" style=\"width:{:.3}%\"></span>\
             </span><span class=\"n\">{n}{}</span></li>\n",
            esc(name),
            f64::from(ok) * 100.0 / f64::from(peak),
            f64::from(failed) * 100.0 / f64::from(peak),
            if failed > 0 {
                format!(" <em>{failed} failed</em>")
            } else {
                String::new()
            },
        ));
    }
    h.push_str("</ul>\n");

    let unknown = s.tool_failures.get("<unknown>").copied().unwrap_or(0);
    if unknown > 0 {
        h.push_str(&format!(
            "<p class=\"note\">{unknown} failure(s) could not be joined to a call — the \
             matching <code>tool_use</code> is not in this transcript.</p>\n"
        ));
    }
    h.push_str("</section>\n");
}

fn file_changes(h: &mut String, s: &Summary) {
    let c = &s.changes;
    h.push_str("<section class=\"card\">\n<h2>Files</h2>\n");
    h.push_str(&format!(
        "<p class=\"big\">{} file(s) <span class=\"add\">+{}</span> \
         <span class=\"del\">−{}</span></p>\n",
        c.files_touched,
        fmt::count(c.lines_added as u64),
        fmt::count(c.lines_deleted as u64),
    ));
    if !c.by_tool.is_empty() {
        // Where the numbers came from, so the reader can check the claim
        // rather than take it. Ordered by calls so the tool that did the most
        // is at the top, and the opaque ones cannot hide at the bottom.
        let mut rows: Vec<(&String, &crate::summary::ToolChanges)> = c.by_tool.iter().collect();
        rows.sort_by(|a, b| b.1.calls.cmp(&a.1.calls).then_with(|| a.0.cmp(b.0)));
        h.push_str("<ul class=\"sources\">\n");
        for (tool, t) in rows {
            let detail = if t.opaque == t.calls {
                "<span class=\"unseen\">no readable diff</span>".to_string()
            } else {
                format!(
                    "{} file(s) <span class=\"add\">+{}</span> <span class=\"del\">−{}</span>{}",
                    t.files_touched,
                    fmt::count(t.lines_added as u64),
                    fmt::count(t.lines_deleted as u64),
                    if t.opaque > 0 {
                        format!(" · <span class=\"unseen\">{} unreadable</span>", t.opaque)
                    } else {
                        String::new()
                    },
                )
            };
            h.push_str(&format!(
                "<li><span class=\"name\">{}</span><span class=\"n\">{}×</span>\
                 <span class=\"d\">{detail}</span></li>\n",
                esc(tool),
                t.calls,
            ));
        }
        h.push_str("</ul>\n");
    }
    if c.opaque_edits > 0 {
        h.push_str(&format!(
            "<p class=\"note unknown\">{} call(s) could have changed files and left no \
             recoverable diff. Those edits are <strong>not</strong> in the counts above — \
             an unknown, not a zero.</p>\n",
            c.opaque_edits
        ));
    }
    h.push_str("</section>\n");
}

fn tokens(h: &mut String, s: &Summary) {
    let t = &s.tokens;
    h.push_str("<section class=\"card\">\n<h2>Tokens</h2>\n<dl class=\"meta\">\n");
    meta(h, "output", fmt::count(t.output));
    meta(h, "thinking", fmt::count(t.thinking));
    meta(h, "input", fmt::count(t.input));
    meta(h, "cache read", fmt::count(t.cache_read));
    meta(h, "cache write", fmt::count(t.cache_write));
    h.push_str("</dl>\n</section>\n");
}

/// Where the user was in the loop — the part a tool histogram cannot show.
fn involvement(h: &mut String, s: &Summary) {
    h.push_str("<section class=\"card\">\n<h2>User involvement</h2>\n");
    if s.user_involvement.is_empty() {
        h.push_str(
            "<p class=\"note\">The user did not speak after the opening prompt — this \
             session ran unattended.</p>\n</section>\n",
        );
        return;
    }
    h.push_str(&format!(
        "<p class=\"note\">{} prompt(s), {} question(s) asked, {} pasted \
         image(s)/document(s).</p>\n",
        s.user_prompts, s.ask_user_questions, s.pasted_attachments
    ));
    h.push_str("<ol class=\"turns\">\n");
    for item in &s.user_involvement {
        let when = item.at().map(|t| clock(&t)).unwrap_or_default();
        match item {
            Involvement::Prompt {
                preview,
                truncated,
                attachments,
                ..
            } => {
                h.push_str(&format!(
                    "<li class=\"prompt\"><span class=\"when\">{}</span>\
                     <span class=\"what\">{}{}{}</span></li>\n",
                    esc(&when),
                    esc(&label_of(preview)),
                    if *truncated { "…" } else { "" },
                    match attachments {
                        0 => String::new(),
                        n => format!(" <span class=\"chip\">+{n} attached</span>"),
                    },
                ));
            }
            Involvement::Question {
                header,
                question,
                options,
                chosen,
                ..
            } => {
                h.push_str(&format!(
                    "<li class=\"ask\"><span class=\"when\">{}</span><span class=\"what\">",
                    esc(&when)
                ));
                if let Some(head) = header {
                    h.push_str(&format!("<span class=\"chip\">{}</span> ", esc(head)));
                }
                h.push_str(&format!("{}<br>", esc(question)));
                match chosen {
                    Some(answer) => h.push_str(&format!(
                        "<span class=\"chose\">chose: {}</span>",
                        esc(answer)
                    )),
                    None => h.push_str("<span class=\"chose none\">no answer recorded</span>"),
                }
                if !options.is_empty() {
                    h.push_str(&format!(
                        " <span class=\"opts\">of {}</span>",
                        esc(&options.join(" · "))
                    ));
                }
                h.push_str("</span></li>\n");
            }
        }
    }
    h.push_str("</ol>\n</section>\n");
}

fn delegation(h: &mut String, s: &Summary) {
    if s.skills.is_empty() && s.subagents.is_empty() {
        // A sidecar can outlive the `Agent` record that spawned it, so the
        // tier is not gated on the chips above having anything to show.
        delegated_tier(h, s);
        return;
    }
    h.push_str("<section class=\"card\">\n<h2>Skills &amp; delegation</h2>\n<p>");
    for skill in &s.skills {
        h.push_str(&format!("<span class=\"chip\">/{}</span> ", esc(skill)));
    }
    for agent in &s.subagents {
        h.push_str(&format!(
            "<span class=\"chip agent\">{}</span> ",
            esc(agent)
        ));
    }
    h.push_str("</p>\n");
    h.push_str("</section>\n");
    delegated_tier(h, s);
}

/// Delegated work, as its own tier with an explicit combined line.
///
/// The tier is separate on purpose: rolling a subagent's 48 tool calls silently
/// into the parent's total would hide exactly the number a reader is here for,
/// and so would leaving them to add it up themselves. Both tiers, then the sum,
/// spelled out.
fn delegated_tier(h: &mut String, s: &Summary) {
    let d = &s.delegation;
    if d.is_empty() {
        return;
    }
    h.push_str("<section class=\"card wide\">\n<h2>Delegated work</h2>\n");

    if !d.spawns.is_empty() {
        h.push_str(
            "<table class=\"tier\">\n<thead><tr><th>agent</th><th>what for</th>\
                    <th class=\"r\">tools</th><th class=\"r\">active</th>\
                    <th class=\"r\">output</th></tr></thead>\n<tbody>\n",
        );
        for spawn in &d.spawns {
            let calls: u32 = spawn.tool_calls.values().sum();
            let failed: u32 = spawn.tool_failures.values().sum();
            h.push_str(&format!(
                "<tr><td><span class=\"chip agent\">{}</span>{}</td><td>{}</td>\
                 <td class=\"r\">{calls}{}</td><td class=\"r\">{}</td>\
                 <td class=\"r\">{}</td></tr>\n",
                esc(spawn.subagent_type.as_deref().unwrap_or("agent")),
                spawn
                    .model
                    .as_deref()
                    .map(|m| format!("<span class=\"sub\">{}</span>", esc(m)))
                    .unwrap_or_default(),
                esc(spawn.description.as_deref().unwrap_or("—")),
                if failed > 0 {
                    format!(" <em>{failed} failed</em>")
                } else {
                    String::new()
                },
                fmt::duration(spawn.active_secs),
                fmt::count(spawn.tokens.output),
            ));
        }
        h.push_str("</tbody>\n</table>\n");
    }

    let delegated_calls: u32 = d.totals.tool_calls.values().sum();
    h.push_str(&format!(
        "<p class=\"combined\">Session <strong>{}</strong> tool call(s) · delegated \
         <strong>{delegated_calls}</strong> · <strong>{}</strong> combined. \
         Output tokens {} + {} = <strong>{}</strong>.</p>\n",
        s.total_tool_calls(),
        s.combined_tool_calls(),
        fmt::count(s.tokens.output),
        fmt::count(d.totals.tokens.output),
        fmt::count(s.combined_output_tokens()),
    ));
    // Seconds are the one thing that does not add: a subagent runs while the
    // parent waits on it, so the two overlap in real time. Said out loud,
    // because a table of per-agent "active" invites the sum.
    h.push_str(
        "<p class=\"note\">Active time is <strong>not</strong> summed: a subagent runs \
         while the session waits on it, so those seconds overlap rather than add.</p>\n",
    );

    if d.unjoined_spawns > 0 {
        h.push_str(&format!(
            "<p class=\"note unknown\">{} spawn(s) left no transcript to read. Their work \
             happened and is <strong>not</strong> in any number here — an unknown, not a \
             zero.</p>\n",
            d.unjoined_spawns
        ));
    }
    if d.inline_records > 0 {
        h.push_str(&format!(
            "<p class=\"note\">{} record(s) in this transcript were subagent turns inlined \
             by an older CLI. They are counted in this tier, not in the session's own \
             totals.</p>\n",
            d.inline_records
        ));
    }
    h.push_str("</section>\n");
}

fn meta(h: &mut String, key: &str, value: impl AsRef<str>) {
    let value = value.as_ref();
    if value.is_empty() {
        return;
    }
    h.push_str(&format!(
        "<dt>{}</dt><dd>{}</dd>\n",
        esc(key),
        esc(value.trim())
    ));
}

fn stat(h: &mut String, key: &str, value: &str, note: &str) {
    h.push_str(&format!(
        "<div class=\"stat\"><span class=\"k\">{}</span><span class=\"v\">{}</span>\
         <span class=\"n\">{}</span></div>\n",
        esc(key),
        esc(value),
        esc(note)
    ));
}

fn join(items: impl Iterator<Item = String>) -> String {
    items.collect::<Vec<_>>().join(", ")
}

fn stamp(t: &DateTime<Utc>) -> String {
    t.to_rfc3339_opts(SecondsFormat::Secs, true)
}

fn clock(t: &DateTime<Utc>) -> String {
    t.format("%m-%d %H:%M:%S").to_string()
}

/// Escape for both element text and double-quoted attributes.
///
/// Tool output and prompt text go straight onto the page, and both routinely
/// contain angle brackets and quotes.
pub(crate) fn esc(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const CSS: &str = r#"
:root{
  --bg:#faf9f7; --panel:#fff; --ink:#1b1a18; --muted:#6d6a63; --line:#e4e0d9;
  --accent:#35618f; --bar:#7ea3c9; --fail:#b8412f; --add:#2f7d4f; --del:#b8412f;
  --user:#4a7c4e; --ask:#a06a1f; --warnbg:#fdf3e6; --chip:#efece6;
  --ph-ink:#fff;
  --ph-exploring:#6b93bd; --ph-implementing:#3f8760; --ph-running:#7a6fa6;
  --ph-filing:#a06a1f; --ph-delegating:#3d8b93; --ph-discussing:#8c887f;
  --ph-mixed:#a8a299;
  --said:#7a4fa0; --saidbg:#f3edf8;
}
@media (prefers-color-scheme: dark){
  :root{
    --bg:#16181a; --panel:#1e2124; --ink:#e6e3dd; --muted:#9a958c; --line:#2f3439;
    --accent:#7fb0e0; --bar:#5b87b5; --fail:#e07a63; --add:#68b884; --del:#e07a63;
    --user:#7cb87f; --ask:#d9a34e; --warnbg:#2c2519; --chip:#2a2e33;
    --ph-ink:#12161a;
    --ph-exploring:#7fa9d1; --ph-implementing:#63b189; --ph-running:#9d92c9;
    --ph-filing:#d9a34e; --ph-delegating:#5fb0b8; --ph-discussing:#9a958c;
    --ph-mixed:#807b73;
    --said:#b998d8; --saidbg:#2a2334;
  }
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
  font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
/* A wide monitor is more information, not more background — but only for the
   panels that can use it. The strip and the card grid take the full width;
   anything prose-shaped keeps a readable measure with its own max-width. */
main{max-width:1480px;margin:0 auto;padding:32px 24px 64px}
h1{font-size:24px;margin:0 0 12px;letter-spacing:-.01em}
h2{font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);
  margin:0 0 12px;font-weight:600}
header{border-bottom:1px solid var(--line);padding-bottom:20px;margin-bottom:20px}
dl.meta{display:grid;grid-template-columns:auto 1fr;gap:2px 14px;margin:0;font-size:13px}
dl.meta dt{color:var(--muted)}
dl.meta dd{margin:0;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  overflow-wrap:anywhere}
header dl.meta{max-width:96ch}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;
  padding:16px 18px;margin-bottom:16px}
.cols{display:grid;gap:16px;align-items:start;
  grid-template-columns:repeat(auto-fit,minmax(300px,1fr))}
.cols>*{min-width:0}
.cols .card{margin-bottom:16px}
/* Wide enough for three: the tool bars get the double track they need and the
   two short panels sit beside them instead of below. */
@media (min-width:1180px){ .cols{grid-template-columns:2fr 1fr 1fr} }
.stats{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:16px}
.stat{flex:1 1 140px;background:var(--panel);border:1px solid var(--line);border-radius:10px;
  padding:12px 14px;display:flex;flex-direction:column;gap:2px}
.stat .k{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
.stat .v{font-size:26px;font-weight:600;letter-spacing:-.02em}
.stat .n{font-size:12px;color:var(--muted)}
.note{font-size:12.5px;color:var(--muted);margin:0 0 10px}
/* Model-written text. Deliberately not a .stat and deliberately not a number:
   a rule down the side, an italic serif face nothing else on the page uses,
   and its own accent, so the one thing here that was written rather than
   counted can never be read as one of the counts. */
.written{border-left:3px solid var(--said);padding:1px 0 1px 16px;margin:0 0 18px;
  max-width:96ch}
.written .said{font:italic 21px/1.4 ui-serif,Georgia,"Times New Roman",serif;
  margin:0 0 5px;color:var(--ink);letter-spacing:-.01em}
/* The attribution annotates the sentence above it and must not compete with
   it. The accent rule, the serif face nothing else on the page uses, and the
   word "written" are three markers already — a bordered chip here was a
   fourth, and it read louder than the headline. */
.written .by{font-size:11.5px;color:var(--muted);margin:0}
.written .by .mark{font-style:italic;font-weight:600;color:var(--said)}
/* Inline, beside a phase's computed kind, the chip IS the marker and stays —
   but tinted rather than outlined, so a row of them does not shout. */
.chip.said{background:var(--saidbg);color:var(--said);border:0;
  font-style:italic;text-transform:none;letter-spacing:0;vertical-align:baseline}
.note.unknown{border-left:3px solid var(--ask);padding-left:9px;margin-top:10px}
.warn{background:var(--warnbg);border:1px solid var(--ask);border-radius:8px;
  padding:10px 14px;font-size:13px;margin:0 0 16px}
.big{font-size:22px;font-weight:600;margin:0}
.add{color:var(--add)} .del{color:var(--del)}

/* time strip */
.strip{display:flex;align-items:stretch;gap:0;border:1px solid var(--line);
  border-radius:8px;overflow-x:auto;overflow-y:hidden;background:var(--bg)}
.span{display:flex;flex-direction:column;min-width:0;flex-shrink:1;flex-basis:0}
.cols-b{display:flex;align-items:flex-end;height:96px;padding:0 1px}
/* Columns fill the width when the session fits, floor at 2px when it does not
   and let the strip scroll — squashing a busy session to nothing would be a
   quieter lie than making the reader scroll. */
.col-b{flex:1 1 0;min-width:2px;display:flex;flex-direction:column;justify-content:flex-end;
  height:100%;padding:0 .5px}
.col-b .mk{display:block;height:7px;margin-bottom:2px;border-radius:2px}
.mk.mkuser{background:var(--user)}
.mk.mkask{background:var(--ask)}
.track{flex:1;display:flex;align-items:flex-end}
.col-b .bar{width:100%;background:var(--bar);border-radius:1px 1px 0 0;min-height:1px}
.col-b .bar.fail{background:var(--fail)}
/* The axis text is gated on the span's rendered width the way the band label
   is. A one-column span used to show the first glyph and a half of its
   timestamp, and two hundred of those made a row of junk under the strip
   (visible in img-638 on #1591). Narrow: nothing. Room for the duration: the
   duration, kept right. Room for both: both. The height is fixed so an empty
   axis still lines up with its neighbours' rules. As a container the axis
   also has no intrinsic width, so a zoomed span is sized by its columns and
   never by its own timestamp. */
.axis{display:flex;justify-content:space-between;font-size:10.5px;line-height:15px;
  min-height:22px;color:var(--muted);padding:4px 3px 2px;border-top:1px solid var(--line);
  gap:6px;white-space:nowrap;overflow:hidden;container-type:inline-size}
.axis span{display:none}
.axis span:last-child{margin-left:auto}
@container (min-width:44px){ .axis span:last-child{display:inline} }
@container (min-width:136px){ .axis span:first-child{display:inline} }
.gap{display:flex;align-items:center;justify-content:center;
  background:repeating-linear-gradient(135deg,transparent 0 4px,var(--line) 4px 5px);
  border-left:1px dashed var(--line);border-right:1px dashed var(--line)}
.strip.roomy .gap{flex:0 0 32px}
.strip.dense .gap{flex:0 0 6px}
/* At this density the dashed borders would be the whole break, so drop them
   and let the hatch itself be the mark. */
.strip.packed .gap{flex:0 0 3px;border-left-width:0;border-right-width:0}
.gap span{font-size:10px;color:var(--muted);background:var(--panel);padding:1px 3px;
  border-radius:3px;transform:rotate(-90deg);white-space:nowrap}
/* zoom in (#1614): CSS only, so the report stays self-contained. Checked, the
   spans stop shrinking and take their content width — which is their
   columns' width, since the bands and the axis are containers and contribute
   none of their own — every column takes a fixed readable width, and the
   strip scrolls. Columns keep flex-grow, so a strip with room to spare still
   fills it: the zoom only ever widens. With width no longer scarce, packed
   breaks get their 6px and dashed edges back. */
.zoom{margin:0 6px 0 0;vertical-align:-1px}
.zoomctl{display:inline-block;font-size:12.5px;color:var(--muted);margin:0 0 10px;
  cursor:pointer;user-select:none}
.zoom:checked ~ .strip .span{flex-basis:auto;flex-shrink:0}
.zoom:checked ~ .strip .col-b{flex-basis:12px;flex-shrink:0}
.zoom:checked ~ .strip.packed .gap{flex-basis:6px;border-left-width:1px;border-right-width:1px}
.legend{display:flex;gap:14px;flex-wrap:wrap;font-size:11.5px;color:var(--muted);
  margin:10px 0 0;align-items:center}
.key{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;
  vertical-align:-1px}
.key.bar{background:var(--bar)} .key.barfail{background:var(--fail)}
.key.mkuser{background:var(--user)} .key.mkask{background:var(--ask)}
.key.gapkey{background:repeating-linear-gradient(135deg,transparent 0 3px,var(--line) 3px 4px);
  border:1px solid var(--line)}

/* phase bands, aligned to the columns beneath them */
.bands{display:flex;gap:1px;padding:0 1px;margin-bottom:3px}
/* The label is drawn only when the band is wide enough to hold it whole.
   Only the browser knows that width — it falls out of the flex share, the
   window and the 2px column floor — so the markup always carries the label
   and the stylesheet decides whether it is shown. Below the bar the colour
   and the tooltip carry the kind, which is what they did all along; what goes
   away is a clipped fragment that carried nothing. A browser without
   container queries keeps the default and reads the same way. */
.band{flex:1 1 0;min-width:0;height:15px;border-radius:3px;overflow:hidden;
  display:flex;align-items:center;justify-content:center;container-type:inline-size}
.band span{display:none;font-size:9.5px;line-height:1;color:var(--ph-ink);
  letter-spacing:.02em;white-space:nowrap;overflow:hidden;padding:0 2px}
@container (min-width:64px){ .band span{display:block} }
.ph-exploring{background:var(--ph-exploring)}
.ph-implementing{background:var(--ph-implementing)}
.ph-running{background:var(--ph-running)}
.ph-filing{background:var(--ph-filing)}
.ph-delegating{background:var(--ph-delegating)}
.ph-discussing{background:var(--ph-discussing)}
.ph-mixed{background:var(--ph-mixed)}
ol.phases li{background:none}
ol.phases li.ph-exploring{border-left-color:var(--ph-exploring)}
ol.phases li.ph-implementing{border-left-color:var(--ph-implementing)}
ol.phases li.ph-running{border-left-color:var(--ph-running)}
ol.phases li.ph-filing{border-left-color:var(--ph-filing)}
ol.phases li.ph-delegating{border-left-color:var(--ph-delegating)}
ol.phases li.ph-discussing{border-left-color:var(--ph-discussing)}
ol.phases li.ph-mixed{border-left-color:var(--ph-mixed)}
ol.phases .chip.kind{color:var(--ink)}
ol.phases .resumed{color:var(--muted);font-style:italic}
ul.bars .fill.ph-exploring{background:var(--ph-exploring)}
ul.bars .fill.ph-implementing{background:var(--ph-implementing)}
ul.bars .fill.ph-running{background:var(--ph-running)}
ul.bars .fill.ph-filing{background:var(--ph-filing)}
ul.bars .fill.ph-delegating{background:var(--ph-delegating)}
ul.bars .fill.ph-discussing{background:var(--ph-discussing)}
ul.bars .fill.ph-mixed{background:var(--ph-mixed)}

/* tool bars */
ul.bars{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:5px}
ul.bars li{display:grid;grid-template-columns:minmax(0,180px) 1fr auto;gap:10px;
  align-items:center;font-size:13px}
ul.bars .name{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
ul.bars .track{height:9px;background:var(--chip);border-radius:5px;overflow:hidden;display:flex}
ul.bars .fill{background:var(--bar);height:100%}
ul.bars .fill.fail{background:var(--fail)}
ul.bars .n{color:var(--muted);font-variant-numeric:tabular-nums;font-size:12px;white-space:nowrap}
ul.bars em{color:var(--fail);font-style:normal}

/* involvement */
ol.turns{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:0}
ol.turns li{display:grid;grid-template-columns:auto 1fr;gap:12px;padding:7px 0 7px 11px;
  border-left:3px solid var(--line);font-size:13.5px}
ol.turns li.prompt{border-left-color:var(--user)}
ol.turns li.ask{border-left-color:var(--ask)}
ol.turns .when{color:var(--muted);font-size:11.5px;font-variant-numeric:tabular-nums;
  padding-top:2px;white-space:nowrap}
ol.turns .what{min-width:0;overflow-wrap:anywhere;max-width:104ch}
.chose{color:var(--accent);font-weight:600;font-size:12.5px}
.chose.none{color:var(--muted);font-weight:400;font-style:italic}
.opts{color:var(--muted);font-size:11.5px}
.chip{display:inline-block;background:var(--chip);border-radius:4px;padding:1px 6px;
  font-size:11.5px;color:var(--muted);white-space:nowrap}
.chip.agent{color:var(--accent)}
code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.92em}
footer{color:var(--muted);font-size:11.5px;border-top:1px solid var(--line);
  padding-top:14px;margin-top:24px}

/* Where a file-change number came from: the audit surface for the adapter
   table. Deliberately quiet — it is there to be checked, not read. */
.sources{list-style:none;margin:.7rem 0 0;padding:0;font-size:.82rem}
.sources li{display:flex;gap:.5rem;align-items:baseline;padding:.18rem 0;
  border-top:1px solid var(--line)}
.sources .name{flex:0 0 auto;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
  color:var(--muted);overflow-wrap:anywhere}
.sources .n{flex:0 0 auto;color:var(--muted);font-variant-numeric:tabular-nums}
.sources .d{flex:1 1 auto;text-align:right}
.unseen{color:var(--ask);font-style:italic}

/* The delegated tier. */
table.tier{width:100%;border-collapse:collapse;font-size:.88rem;margin-top:.4rem}
table.tier th{text-align:left;font-weight:600;color:var(--muted);font-size:.75rem;
  text-transform:uppercase;letter-spacing:.04em;padding:.3rem .5rem;
  border-bottom:1px solid var(--line)}
table.tier td{padding:.42rem .5rem;border-bottom:1px solid var(--line);
  vertical-align:top}
table.tier .r{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
table.tier .sub{display:block;color:var(--muted);font-size:.72rem;margin-top:.15rem;
  font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
p.combined{margin:.7rem 0 .2rem;padding:.55rem .7rem;background:var(--chip);
  border-radius:6px;font-size:.9rem}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::summary::{Summary, summarize};
    use crate::transcript::{Subagent, Transcript};

    fn render_lines(lines: &[&str]) -> String {
        let t = Transcript {
            records: lines
                .iter()
                .map(|l| serde_json::from_str(l).unwrap())
                .collect(),
            skipped: 0,
        };
        report(&summarize(None, &t, &[]))
    }

    /// The facts JSON is a contract, and the renderer is its first consumer:
    /// a report built from a *serialized* facts document must be identical to
    /// one built from the summary in memory. If this drifts, the seam a future
    /// front-end plugs into has quietly stopped being real.
    #[test]
    fn a_report_from_serialized_facts_is_identical() {
        let t = Transcript {
            records: [
                r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                    "content":"start"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T10:00:20.000Z","message":{
                    "model":"claude-opus-5","usage":{"output_tokens":40},
                    "content":[{"type":"tool_use","id":"t1","name":"AskUserQuestion","input":{
                        "questions":[{"question":"Now?","header":"When",
                        "options":[{"label":"Yes"}]}]}}]}}"#,
                r#"{"type":"user","timestamp":"2026-08-20T10:04:00.000Z","message":{"content":[
                    {"type":"tool_result","tool_use_id":"t1","is_error":true}]},
                    "toolUseResult":{"answers":{"Now?":"Yes"}}}"#,
            ]
            .iter()
            .map(|l| serde_json::from_str(l).unwrap())
            .collect(),
            skipped: 0,
        };
        let direct = summarize(None, &t, &[]);
        let json = serde_json::to_string(&direct).unwrap();
        let round_tripped: Summary = serde_json::from_str(&json).unwrap();
        assert_eq!(report(&direct), report(&round_tripped));
        // the parts a shallow round trip would lose: the tagged involvement
        // enum, and the activity series it is positioned against
        let html = report(&round_tripped);
        assert!(html.contains("chose: Yes"), "answer lost in the round trip");
        assert!(
            html.contains("3m idle"),
            "idle break lost in the round trip"
        );
        assert_eq!(round_tripped.activity.spans.len(), 2);
        assert_eq!(round_tripped.tokens.output, 40);
    }

    /// The delegated tier on the page: both tiers visible, and the sum stated
    /// rather than left as an exercise. A report that shows "1 tool call" for a
    /// session whose subagent ran fifty is the undercount this sprint exists to
    /// fix, and it would be just as wrong to fix it by quietly adding them up.
    #[test]
    fn the_report_shows_delegated_work_beside_the_parents_and_states_the_sum() {
        let parent = Transcript {
            records: [
                r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                    "content":"map it"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T10:00:05.000Z","message":{
                    "usage":{"output_tokens":100},
                    "content":[{"type":"tool_use","id":"t1","name":"Agent",
                                "input":{"subagent_type":"Explore"}}]}}"#,
                r#"{"type":"user","timestamp":"2026-08-20T10:00:40.000Z","toolUseResult":{
                    "agentId":"a1","description":"Map the linking layer",
                    "resolvedModel":"claude-opus-5"},
                    "message":{"content":[{"type":"tool_result","tool_use_id":"t1"}]}}"#,
            ]
            .iter()
            .map(|l| serde_json::from_str(l).unwrap())
            .collect(),
            skipped: 0,
        };
        let spawned = Subagent {
            agent_id: Some("a1".to_string()),
            transcript: Transcript {
                records: [r#"{"type":"assistant","isSidechain":true,"agentId":"a1",
                        "timestamp":"2026-08-20T10:00:10.000Z","message":{
                        "usage":{"output_tokens":900},
                        "content":[{"type":"tool_use","id":"s1","name":"Grep"},
                                   {"type":"tool_use","id":"s2","name":"Read"}]}}"#]
                .iter()
                .map(|l| serde_json::from_str(l).unwrap())
                .collect(),
                skipped: 0,
            },
        };
        let direct = summarize(None, &parent, std::slice::from_ref(&spawned));
        let html = report(&direct);

        assert!(html.contains("Delegated work"));
        assert!(html.contains("Map the linking layer"), "what it was for");
        assert!(html.contains("claude-opus-5"), "which model actually ran");
        assert!(
            html.contains("<strong>3</strong> combined"),
            "the combined line must be on the page, not left to the reader"
        );
        assert!(
            html.contains("2 more delegated"),
            "the headline must say the tool count is not the whole story"
        );
        assert!(
            html.contains("not</strong> summed"),
            "overlapping seconds must be called out, not implied"
        );

        // And the tier survives the contract seam like everything else.
        let json = serde_json::to_string(&direct).unwrap();
        let round_tripped: Summary = serde_json::from_str(&json).unwrap();
        assert_eq!(report(&round_tripped), html);
    }

    /// No network, ever. The assertions name the constructs that actually
    /// *fetch*, not the substring "https://" — a session where the user pasted
    /// a URL puts that text on the page as escaped prose, which reaches
    /// nothing. Confusing the two would make this test fire on real sessions
    /// and teach the next person to weaken it.
    #[test]
    fn the_report_is_self_contained() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"go, see https://example.invalid/spec"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:30.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Read"}]}}"#,
        ]);
        assert!(html.starts_with("<!doctype html>"));
        for probe in [
            "<script", "<link", "<img", "<iframe", "<object", "<embed", "src=", "@import", "url(",
        ] {
            assert!(!html.contains(probe), "report can fetch: {probe}");
        }
        // The pasted URL is still on the page — as text, which is the point.
        assert!(html.contains("https://example.invalid/spec"));
    }

    /// A raw failure count says nothing without its denominator (#1590): 45
    /// failed of 2,777 is a different session from 45 of 90. The rate is over
    /// the calls — a failed call is a call, counted once — and the zero case
    /// stays bare.
    #[test]
    fn the_headline_puts_the_failure_rate_beside_the_count() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"go"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:10.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Bash"},
                           {"type":"tool_use","id":"t2","name":"Bash"},
                           {"type":"tool_use","id":"t3","name":"Read"},
                           {"type":"tool_use","id":"t4","name":"Read"}]}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:20.000Z","message":{
                "content":[{"type":"tool_result","tool_use_id":"t1","is_error":true}]}}"#,
        ]);
        assert!(
            html.contains(r#"<span class="n">1 failed · 25.00%</span>"#),
            "one of four, over the calls"
        );

        // No failures reads as it did: `none failed`, with no `0.00%` beside it.
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"go"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:10.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Read"}]}}"#,
        ]);
        assert!(html.contains(r#"<span class="n">none failed</span>"#));

        // A failure whose call is not in the file is blamed on `<unknown>` and
        // is not among the calls either: it is counted, it is explained, and
        // it does not put a 200% beside a count of two.
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"go"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:10.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Read"}]}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:20.000Z","message":{
                "content":[{"type":"tool_result","tool_use_id":"gone","is_error":true},
                           {"type":"tool_result","tool_use_id":"gone2","is_error":true}]}}"#,
        ]);
        assert!(
            html.contains(r#"<span class="n">2 failed</span>"#),
            "no rate when no failure joined a call"
        );
        assert!(html.contains("could not be joined"));
    }

    /// Past a few hundred columns the strip is a wall of 2px bars and no
    /// narrowing of the breaks reads (#1591). Until the front-end zooms for
    /// real, a checkbox — CSS `:checked`, no script — sets every column to a
    /// readable fixed width and lets the strip scroll (#1614). It is offered
    /// only where it would change something.
    #[test]
    fn a_dense_strip_offers_a_zoom_in_and_a_short_one_does_not() {
        // One record a minute for twelve minutes: one stretch on 5s columns,
        // 145 of them — over the threshold, and well under MAX_BUCKETS.
        let lines: Vec<String> = (0..=12)
            .map(|i| format!(r#"{{"type":"user","timestamp":"2026-08-20T10:{i:02}:00.000Z"}}"#))
            .collect();
        let refs: Vec<&str> = lines.iter().map(String::as_str).collect();
        let html = render_lines(&refs);
        assert!(html.contains(r#"<input type="checkbox" id="zoom" class="zoom">"#));
        // The control must precede the strip as its sibling — `:checked ~ .strip`
        // is the whole mechanism, and a wrapper would silently break it.
        let input = html.find(r#"id="zoom""#).expect("control");
        let strip = html.find(r#"<div class="strip "#).expect("strip");
        assert!(
            input < strip,
            "the checkbox comes before the strip it zooms"
        );
        assert!(
            html.contains(&format!(
                ".zoom:checked ~ .strip .col-b{{flex-basis:{ZOOM_COLUMN_PX}px"
            )),
            "the stylesheet sets the reference column width"
        );
        assert!(!html.contains("<script"), "still no script");

        // Two records a minute apart: thirteen columns, nothing to zoom.
        let html = render_lines(&refs[..2]);
        assert!(!html.contains(r#"id="zoom""#));
    }

    /// Wall clock stays on the page — trap #2 exists because active-alone is
    /// dishonest about a resumed session — but it is no longer a tile of its
    /// own competing with active for the eye.
    #[test]
    fn wall_clock_is_kept_but_is_no_longer_a_peer_of_active() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"go"}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:30.000Z"}"#,
            r#"{"type":"user","timestamp":"2026-08-20T12:00:30.000Z"}"#,
        ]);
        assert!(
            html.contains(r#"<span class="k">active</span>"#),
            "active is still the headline"
        );
        assert!(
            !html.contains(r#"<span class="k">wall</span>"#),
            "wall no longer has a tile of its own"
        );
        // ...but the number itself is still there, and so is idle.
        assert!(html.contains("over 2h00m wall · 2h00m idle"));
    }

    #[test]
    fn the_strip_carries_a_band_for_each_phase() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"look around"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:20.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Read"}]}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:40.000Z","message":{
                "content":"now change it"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:01:00.000Z","message":{
                "content":[{"type":"tool_use","id":"t2","name":"Edit"}]}}"#,
        ]);
        assert!(html.contains(r#"class="band ph-exploring""#));
        assert!(html.contains(r#"class="band ph-implementing""#));
        // The phase that was opened by a prompt says which prompt.
        assert!(html.contains("now change it"));
        // 40s exploring against 20s implementing: the headline names the kind
        // that holds the most *time*, not the one that ran last.
        assert!(html.contains("mostly exploring"));
    }

    /// A phase the strip cannot draw is still a phase. Same instinct as
    /// `opaque_edits`: what the page cannot show, it says it cannot show.
    #[test]
    fn a_phase_too_short_to_draw_is_counted_rather_than_dropped() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"one"}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:01.000Z","message":{
                "content":"two"}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:02.000Z","message":{
                "content":"three"}}"#,
        ]);
        // Three phases inside a two-second span: one bucket, one band.
        assert!(html.contains("2 phase(s) are shorter than one column"));
        assert!(html.contains("not the same as their not existing"));
    }

    /// The phase durations are the answer to "where did the time go", so
    /// within a stretch of work they have to account for all of it.
    #[test]
    fn phase_durations_account_for_every_second_of_their_span() {
        let t = Transcript {
            records: [
                r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                    "content":"a"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T10:00:20.000Z","message":{
                    "content":[{"type":"tool_use","id":"t1","name":"Read"}]}}"#,
                r#"{"type":"user","timestamp":"2026-08-20T10:01:40.000Z","message":{
                    "content":"b"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T12:00:00.000Z","message":{
                    "content":[{"type":"tool_use","id":"t2","name":"Edit"}]}}"#,
            ]
            .iter()
            .map(|l| serde_json::from_str(l).unwrap())
            .collect(),
            skipped: 0,
        };
        let s = summarize(None, &t, &[]);
        assert_eq!(
            s.phases.iter().map(|p| p.secs).sum::<i64>(),
            s.activity.spans.iter().map(|sp| sp.secs).sum::<i64>()
        );
        assert!(report(&s).contains("account for all of it"));
    }

    #[test]
    fn prompt_text_is_escaped_rather_than_injected() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"fix <img onerror=x> & \"quotes\""}}"#,
        ]);
        assert!(html.contains("fix &lt;img onerror=x&gt; &amp; &quot;quotes&quot;"));
        assert!(!html.contains("<img onerror"));
    }

    #[test]
    fn an_opaque_edit_is_reported_as_unknown_not_as_zero() {
        let html = render_lines(&[
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"Bash"}]}}"#,
        ]);
        assert!(html.contains("recoverable diff"));
        assert!(html.contains("an unknown, not a zero"));
    }

    #[test]
    fn idle_is_drawn_as_a_collapsed_break() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z"}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:30.000Z"}"#,
            r#"{"type":"user","timestamp":"2026-08-20T12:00:30.000Z"}"#,
        ]);
        assert!(html.contains(r#"class="gap" title="2h00m idle""#));
    }

    /// The strip exists to collapse idle, so idle must not end up owning it.
    /// At 209 stretches the fixed 6px breaks claimed 1248px while the work
    /// columns sat on their 2px floor — 72% of the panel was hatching. Found
    /// by looking at a rendered report, not by a test.
    #[test]
    fn breaks_narrow_once_they_would_crowd_out_the_work() {
        // One record every ten minutes: every gap is idle, so records == spans.
        let lines: Vec<String> = (0..NARROW_BREAKS_MIN + 5)
            .map(|i| {
                format!(
                    r#"{{"type":"user","timestamp":"2026-08-20T{:02}:{:02}:00.000Z"}}"#,
                    10 + (i * 10) / 60,
                    (i * 10) % 60
                )
            })
            .collect();
        let refs: Vec<&str> = lines.iter().map(String::as_str).collect();
        let html = render_lines(&refs);
        assert!(html.contains(r#"<div class="strip packed">"#));

        // A moderate session keeps the wider, more legible break.
        let html = render_lines(&refs[..20]);
        assert!(html.contains(r#"<div class="strip dense">"#));

        // And a short one still labels them.
        let html = render_lines(&refs[..5]);
        assert!(html.contains(r#"<div class="strip roomy">"#));
    }

    /// On the corpus's 209-span session every band is a few pixels wide, so
    /// every label was clipped to nothing and the band row degraded to an
    /// unreadable stripe — on exactly the session phases were built to make
    /// legible. The label is now gated on the band's *rendered* width, which
    /// only the browser knows, so the markup always carries it and the
    /// stylesheet decides whether it is shown.
    #[test]
    fn a_band_too_narrow_for_its_label_shows_colour_and_tooltip_instead() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":"read it"}}"#,
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:30.000Z","message":{
                "content":[{"type":"tool_use","name":"Read"}]}}"#,
        ]);

        // The kind is never carried by the label alone: the band's class is
        // the colour and its tooltip names the phase in words.
        assert!(html.contains(r#"<div class="band ph-exploring""#));
        assert!(html.contains("title=\"exploring · "));

        // Hidden by default, shown only once the band is wide enough to hold
        // the longest label whole. A browser without container queries keeps
        // the default and falls back to colour and tooltip — the same reading,
        // never a clipped one.
        assert!(CSS.contains("container-type:inline-size"));
        assert!(CSS.contains(".band span{display:none"));
        assert!(CSS.contains(&format!("@container (min-width:{BAND_LABEL_MIN_PX}px)")));

        // And the reader is told where the colours are named.
        assert!(html.contains("Band colours name the phase kind"));
    }

    /// A 54-day session must not render its wall clock as `1297h15m` — that
    /// is the number #1557 moved into the sub-label to keep it readable.
    #[test]
    fn a_multi_day_wall_clock_reads_in_days() {
        let html = render_lines(&[
            r#"{"type":"user","timestamp":"2026-06-13T00:47:18.000Z"}"#,
            r#"{"type":"user","timestamp":"2026-08-06T02:02:39.000Z"}"#,
        ]);
        assert!(
            html.contains("over 54d01h wall"),
            "wall clock still in hours"
        );
        assert!(!html.contains("1297h"));
    }

    fn labelled(s: &mut Summary, headline: &str, phases: &[&str]) {
        s.labels = Some(crate::label::Labels {
            headline: headline.to_string(),
            phases: phases
                .iter()
                .enumerate()
                .map(|(i, l)| crate::label::PhaseLabel {
                    phase: i,
                    label: l.to_string(),
                })
                .collect(),
            model: "fake-1".to_string(),
            prompt_version: "headline.v1".to_string(),
            facts_digest: "sha256:0000".to_string(),
            generated: "2026-08-20T11:00:00Z".parse().unwrap(),
        });
    }

    fn two_phase_facts() -> Summary {
        let t = Transcript {
            records: [
                r#"{"type":"user","timestamp":"2026-08-20T10:00:00.000Z","message":{
                    "content":"read the parser"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T10:00:20.000Z","message":{
                    "usage":{"output_tokens":40},
                    "content":[{"type":"tool_use","id":"t1","name":"Read","input":{}}]}}"#,
                r#"{"type":"user","timestamp":"2026-08-20T10:05:00.000Z","message":{
                    "content":"now fix it"}}"#,
                r#"{"type":"assistant","timestamp":"2026-08-20T10:06:00.000Z","message":{
                    "usage":{"output_tokens":90},
                    "content":[{"type":"tool_use","id":"t2","name":"Edit","input":{}}]}}"#,
            ]
            .iter()
            .map(|l| serde_json::from_str(l).unwrap())
            .collect(),
            skipped: 0,
        };
        summarize(None, &t, &[])
    }

    /// No labels is the *default* path, not a degraded one. The page must be
    /// finished without a headline — no empty block, no stray rule, and no
    /// footer claiming an attribution nobody made.
    #[test]
    fn without_labels_the_headline_is_absent_rather_than_empty() {
        let html = report(&two_phase_facts());
        assert!(
            !html.contains("class=\"written\""),
            "empty written block drawn"
        );
        assert!(
            !html.contains("chip said"),
            "written chip drawn with nothing to say"
        );
        assert!(
            html.contains("nothing here is inferred"),
            "a page with no model text should still say so"
        );
    }

    /// The whole point of the seam: a reader must be able to tell, on the
    /// page, which words were written and which were counted. If the headline
    /// ever renders unmarked or borrows the styling the numbers use, the
    /// report has handed over the exact confusion this project avoids.
    #[test]
    fn model_written_text_is_marked_as_written_wherever_it_appears() {
        let mut s = two_phase_facts();
        labelled(
            &mut s,
            "Read the parser and fixed it.",
            &["reading the parser", "fixing it"],
        );
        let html = report(&s);

        assert!(html.contains("Read the parser and fixed it."));
        assert!(
            html.contains("class=\"written\""),
            "headline block unmarked"
        );
        assert!(html.contains("chip said"), "written text carries no marker");
        assert!(
            html.contains("written by fake-1 (headline.v1)"),
            "the model is not named beside its own text"
        );
        // The footer's old blanket claim is now false and must not survive.
        assert!(
            !html.contains("nothing here is inferred"),
            "footer still claims nothing on the page was written"
        );
        assert!(
            html.contains("not measured"),
            "footer does not say which is which"
        );

        // A written label stands *beside* the mechanical kind, never over it.
        assert!(html.contains("reading the parser"), "phase label missing");
        assert!(
            html.contains(">exploring<") || html.contains(">implementing<"),
            "the computed phase kind was displaced by the written label"
        );
    }

    /// A model writes the text, so the text is untrusted input. Same rule as
    /// user prompts, one layer further out.
    #[test]
    fn a_headline_is_escaped_rather_than_injected() {
        let mut s = two_phase_facts();
        labelled(&mut s, "<script>alert(1)</script>", &["<img onerror=x>"]);
        let html = report(&s);
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(!html.contains("<img onerror=x>"));
        assert!(html.contains("&lt;script&gt;"));
    }

    /// Labels ride the facts document like everything else: `render --from`
    /// must show them without any model call, and identically.
    #[test]
    fn labels_survive_the_facts_round_trip() {
        let mut s = two_phase_facts();
        labelled(
            &mut s,
            "Read the parser and fixed it.",
            &["reading", "fixing"],
        );
        let json = serde_json::to_string(&s).unwrap();
        let round_tripped: Summary = serde_json::from_str(&json).unwrap();
        assert_eq!(report(&s), report(&round_tripped));
        assert!(report(&round_tripped).contains("Read the parser and fixed it."));
    }

    /// A facts document written before labels existed has no `labels` key at
    /// all. It must still parse, and still render — the field is additive.
    #[test]
    fn facts_without_a_labels_key_still_parse() {
        let mut json = serde_json::to_value(two_phase_facts()).unwrap();
        assert!(
            json.as_object().unwrap().get("labels").is_none(),
            "an unlabelled document must not carry a null labels key"
        );
        json.as_object_mut().unwrap().remove("labels");
        let s: Summary = serde_json::from_value(json).unwrap();
        assert!(s.labels.is_none());
        report(&s);
    }

    #[test]
    fn a_question_shows_what_was_asked_and_chosen() {
        let html = render_lines(&[
            r#"{"type":"assistant","timestamp":"2026-08-20T10:00:00.000Z","message":{
                "content":[{"type":"tool_use","id":"t1","name":"AskUserQuestion","input":{
                    "questions":[{"question":"Which store?","header":"Store",
                    "options":[{"label":"Postgres"},{"label":"SQLite"}]}]}}]}}"#,
            r#"{"type":"user","timestamp":"2026-08-20T10:00:20.000Z","message":{"content":[
                {"type":"tool_result","tool_use_id":"t1"}]},
                "toolUseResult":{"answers":{"Which store?":"SQLite"}}}"#,
        ]);
        assert!(html.contains("Which store?"));
        assert!(html.contains("chose: SQLite"));
        assert!(html.contains("Postgres · SQLite"));
    }
}
